# Generated by Django 4.2.14 on 2024-07-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='header',
            field=models.TextField(blank=True, max_length=128, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to='files/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified Date'),
        ),
    ]
