# Generated by Django 4.2.14 on 2024-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_body_alter_note_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to='files/{image}/', verbose_name='Image'),
        ),
    ]
