# Generated by Django 4.2.14 on 2024-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to='files/<django.db.models.fields.TextField>/', verbose_name='Image'),
        ),
    ]
